name: Task Proposal Converter

on:
  # Trigger when issues are labeled (proposal approval process)
  issues:
    types: [labeled, unlabeled]

  # Manual trigger for processing
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (no actual changes)'
        required: false
        default: false
        type: boolean

permissions:
  issues: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  convert-proposals:
    # Only run if:
    # 1. Not triggered by automation
    # 2. Issue has proposal and approved labels
    # 3. Not a DSR or automated issue
    if: |
      github.actor != 'github-actions[bot]' &&
      !contains(github.event.issue.title, 'Daily Status Report') &&
      !contains(github.event.issue.title, '[automated]') &&
      !startsWith(github.event.issue.title, '.github/') &&
      (
        (github.event_name == 'issues' && 
         contains(github.event.issue.labels.*.name, 'proposal') &&
         contains(github.event.issue.labels.*.name, 'approved')) ||
        github.event_name == 'workflow_dispatch'
      )
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub==2.1.1

      - name: Convert Proposals to Tasks
        working-directory: Actions/TaskProposal
        run: |
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "DRY RUN MODE - No changes will be made"
            python task_converter.py --dry-run
          else
            python task_converter.py
          fi

      - name: Summary
        run: |
          echo "Task proposal conversion completed"
          echo "Check the logs above for details"